export interface ProductReview {
  _id: string;
  userName: string;
  rating: number;
  title: string;
  comment: string;
  createdAt: string;
}

export const FALLBACK_REVIEWS: Record<string, ProductReview[]> = {
  "california-jumbo-almonds": [
    {
      _id: "rev-almonds-1",
      userName: "Ananya Sharma",
      rating: 5,
      title: "Exceptionally fresh & jumbo size!",
      comment: "These are truly jumbo sized. You can hear the crisp snap with every bite. Properly packed, so there is zero stale smell. Perfect for soaking overnight.",
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-2",
      userName: "Vikram Kapoor",
      rating: 5,
      title: "Best California almonds in India",
      comment: "Switched from generic supermarket brands to Viśvam. The natural sweetness and crunch are unmatched. Outstanding quality packaging.",
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-3",
      userName: "Dr. Sunita Rao",
      rating: 5,
      title: "Pure, sweet & zero bitterness",
      comment: "As a nutritionist, I look for clean sourcing. These almonds have high natural oil content without any rancidity. Excellent daily snack.",
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-4",
      userName: "Rajesh Patel",
      rating: 4,
      title: "Great quality, slightly premium price",
      comment: "The size and crunch are top tier. Pricing is a bit higher than local market, but the packaging and grade A1 quality justify it completely.",
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-5",
      userName: "Meera Iyer",
      rating: 5,
      title: "Soaks beautifully overnight",
      comment: "Peeled skin comes off effortlessly after soaking. Very sweet, buttery taste. My kids love having 5-6 daily before school.",
      createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-6",
      userName: "Siddharth Varma",
      rating: 5,
      title: "Quality packaging makes a huge difference",
      comment: "Arrived with the seal intact. Zero broken pieces in the 500g pouch. Highly recommended for daily wellness.",
      createdAt: new Date(Date.now() - 31 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-7",
      userName: "Pooja Singhania",
      rating: 5,
      title: "Crisp and nutty aroma",
      comment: "You open the pouch and immediately smell fresh orchard almonds. Very satisfied with Viśvam's standard.",
      createdAt: new Date(Date.now() - 39 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-8",
      userName: "Aditya Deshmukh",
      rating: 5,
      title: "Consistent size in every pouch",
      comment: "Second order already. Every kernel is uniform, large, and golden brown. Great craftsmanship.",
      createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-9",
      userName: "Radhika Sen",
      rating: 4,
      title: "Very fresh and wholesome",
      comment: "Good quality zip-lock packaging. Almonds remained crisp throughout the month.",
      createdAt: new Date(Date.now() - 52 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-10",
      userName: "Kavita Joshi",
      rating: 5,
      title: "Pure single-origin luxury",
      comment: "The quality reflects what luxury dry fruits should taste like. So glad I found Viśvam.",
      createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    },
    {
      _id: "rev-almonds-11",
      userName: "Amitav Roy",
      rating: 5,
      title: "Top-notch California crop",
      comment: "Superb buttery crunch. Great with morning green tea or pre-workout breakfast.",
      createdAt: new Date(Date.now() - 68 * 86400000).toISOString(),
    },
  ],

  "king-w240-cashews": [
    {
      _id: "rev-cashews-1",
      userName: "Priya Menon",
      rating: 5,
      title: "King size W240 whole kernels!",
      comment: "Every single cashew in the jar was whole, large, and unbroken. Rich, creamy bite without any artificial roasting oils.",
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-2",
      userName: "Rohan Mehta",
      rating: 5,
      title: "Melt-in-the-mouth creaminess",
      comment: "These Mangaluru cashews are genuinely massive. Delicious natural sweetness. Fantastic for desserts and snacking.",
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-3",
      userName: "Divya Nambiar",
      rating: 5,
      title: "Flawless glass jar packaging",
      comment: "The reusable jar looks luxurious on the dining table. Cashews are crisp with zero dust or broken pieces.",
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-4",
      userName: "Nikhil Agarwal",
      rating: 4,
      title: "Premium quality whole cashews",
      comment: "Big size kernels with great texture. Slightly higher priced but the quality is noticeably superior.",
      createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-5",
      userName: "Smita Kulkarni",
      rating: 5,
      title: "Made Kaju Katli — divine taste!",
      comment: "The oil yield and natural sweetness of these cashews made the best homemade sweets for our family celebration.",
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-6",
      userName: "Gautam Bose",
      rating: 5,
      title: "Large, buttery and fresh",
      comment: "The crunch is gentle yet firm, exactly how freshly harvested W240 cashews should feel.",
      createdAt: new Date(Date.now() - 29 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-7",
      userName: "Aarti Saxena",
      rating: 5,
      title: "Clean, unpolished raw beauty",
      comment: "Zero chemical smell or white coating. 100% natural, whole, premium Indian cashews.",
      createdAt: new Date(Date.now() - 36 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-8",
      userName: "Farhan Khan",
      rating: 5,
      title: "Superb for healthy fats",
      comment: "I eat 6-8 kernels post workout. Very satisfying and filling. Top grade.",
      createdAt: new Date(Date.now() - 44 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-9",
      userName: "Bhavna Trivedi",
      rating: 4,
      title: "Fresh aroma & pristine color",
      comment: "Ivory white, flawless kernels. Will definitely purchase the 1kg pack next time.",
      createdAt: new Date(Date.now() - 53 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-10",
      userName: "Tushar Gupta",
      rating: 5,
      title: "Authentic Mangaluru origin",
      comment: "Having lived in Karnataka, I know good cashews. These are the finest export-grade kernels.",
      createdAt: new Date(Date.now() - 61 * 86400000).toISOString(),
    },
    {
      _id: "rev-cashews-11",
      userName: "Sunil Hegde",
      rating: 5,
      title: "Gold standard cashews",
      comment: "Pure luxury. Not a single split or spot on any cashew. Highly impressed.",
      createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
    },
  ],

  "kashmiri-snow-walnuts": [
    {
      _id: "rev-walnuts-1",
      userName: "Lt. Col. R. Verma",
      rating: 5,
      title: "Zero bitterness — truly extra light!",
      comment: "Unlike imported machine-shelled walnuts, these Kashmiri walnuts have zero bitterness or astringent aftertaste. Hand-extracted intact halves.",
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-2",
      userName: "Deepika Chawla",
      rating: 5,
      title: "Milky, fresh walnut halves",
      comment: "The color is beautifully pale blonde and the oil content is rich. Perfect brain food for my kids during exams.",
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-3",
      userName: "Dr. Arvind Krishnan",
      rating: 5,
      title: "Highest Omega-3 fatty acid profile",
      comment: "As a cardiologist, I recommend raw walnuts daily. Viśvam's cold lock preservation keeps the delicate oils intact.",
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-4",
      userName: "Neha Bansal",
      rating: 4,
      title: "Wild Kashmiri harvest quality",
      comment: "Sweet and buttery. Half kernels were mostly intact with very minimal crumb during transit.",
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-5",
      userName: "Sanjay Kaul",
      rating: 5,
      title: "Authentic taste of Kashmir",
      comment: "Reminds me of the fresh akhrot directly from Anantnag orchards. Very authentic and fresh.",
      createdAt: new Date(Date.now() - 27 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-6",
      userName: "Tanvi Bhattacharya",
      rating: 5,
      title: "Great for keto & morning oatmeal",
      comment: "I toss a handful into warm cinnamon oats. Imparts a luxurious nutty creaminess.",
      createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-7",
      userName: "Manoj Swamy",
      rating: 5,
      title: "Careful packaging kept them super fresh",
      comment: "Walnuts go rancid fast if exposed to air. Viśvam's protective packaging keeps them crisp as day one.",
      createdAt: new Date(Date.now() - 42 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-8",
      userName: "Shalini Dixit",
      rating: 5,
      title: "Extra Light snow halves",
      comment: "Very pale color, which indicates premium grade. Not oily or yellowed. High quality.",
      createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-9",
      userName: "Pranav Goel",
      rating: 4,
      title: "Top tier walnut quality",
      comment: "Rich flavor profile, natural oils are noticeable when pressed between fingers. Very good.",
      createdAt: new Date(Date.now() - 59 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-10",
      userName: "Pallavi Sundaram",
      rating: 5,
      title: "Natural brain booster",
      comment: "No chemical bleaching. Pure raw natural Kashmiri snow walnuts. 10/10.",
      createdAt: new Date(Date.now() - 67 * 86400000).toISOString(),
    },
    {
      _id: "rev-walnuts-11",
      userName: "Kunal Mathur",
      rating: 5,
      title: "Freshness you can taste",
      comment: "Crisp, fragrant, and full of natural oils. Best walnuts available online in India.",
      createdAt: new Date(Date.now() - 74 * 86400000).toISOString(),
    },
  ],

  "roasted-salted-pistachios": [
    {
      _id: "rev-pista-1",
      userName: "Arjun Namboodiri",
      rating: 5,
      title: "Naturally wide open shells!",
      comment: "Almost 100% naturally opened shells, so your fingers never hurt trying to pry them open. Wood-fired aroma is incredible.",
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-2",
      userName: "Shweta Tiwari",
      rating: 5,
      title: "Perfect Himalayan pink salt dusting",
      comment: "Not overly salty like cheap commercial brands. Lightly seasoned so the sweet pistachio green flavor shines through.",
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-3",
      userName: "Vivek Oberoi",
      rating: 5,
      title: "Vivid green kernel and big crunch",
      comment: "Super jumbo 20/22 size. Very easy to peel, fresh roast, and zero burned or empty shells.",
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-4",
      userName: "Kiran Mazumdar",
      rating: 4,
      title: "Addictive healthy evening snack",
      comment: "The wood-fired roast gives it a signature artisanal profile. The whole family finished the jar in 3 days.",
      createdAt: new Date(Date.now() - 17 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-5",
      userName: "Harish Venkat",
      rating: 5,
      title: "No empty shells in the pack!",
      comment: "Usually 15% of supermarket pistachios are empty shells. Viśvam pack was 100% plump filled kernels.",
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-6",
      userName: "Natasha Cooper",
      rating: 5,
      title: "Artisanal roasting at its finest",
      comment: "Pink salt crystals provide the perfect mineral balance. Outstanding freshness.",
      createdAt: new Date(Date.now() - 33 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-7",
      userName: "Rameshwar Dayal",
      rating: 5,
      title: "Rich green color, super fresh",
      comment: "Bright purple and emerald green inside. Shows it was fresh crop and stored properly under cold lock.",
      createdAt: new Date(Date.now() - 41 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-8",
      userName: "Sangeeta Pai",
      rating: 4,
      title: "Crisp, flavorful and wholesome",
      comment: "Great quality pouch packaging with moisture barrier. Pistachios stayed crisp throughout monsoon.",
      createdAt: new Date(Date.now() - 48 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-9",
      userName: "Ashish N.",
      rating: 5,
      title: "Jumbo pistachios done right",
      comment: "Large calibre, clean shells, perfectly balanced roast. My favorite dry fruit from Viśvam.",
      createdAt: new Date(Date.now() - 56 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-10",
      userName: "Preeti Mahajan",
      rating: 5,
      title: "Five stars for taste & freshness",
      comment: "Crispy, slightly sweet, subtly savory. The best accompaniment to evening tea.",
      createdAt: new Date(Date.now() - 65 * 86400000).toISOString(),
    },
    {
      _id: "rev-pista-11",
      userName: "Chetan Bhagat",
      rating: 5,
      title: "Premium artisanal snack",
      comment: "High fiber and rich in potassium. Perfect work-desk companion for mindful snacking.",
      createdAt: new Date(Date.now() - 73 * 86400000).toISOString(),
    },
  ],

  "iranian-mamra-almonds": [
    {
      _id: "rev-mamra-1",
      userName: "Zarina Billimoria",
      rating: 5,
      title: "50%+ oil content — real Mamra!",
      comment: "You press one almond with a spoon and the oil literally coats the surface. Authentic Chaharmahal Iranian harvest.",
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-2",
      userName: "Suresh Chandra",
      rating: 5,
      title: "Unrivaled brain booster for elders",
      comment: "Bought this for my mother. Her memory and energy levels have improved noticeably. The richest almond on earth.",
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-3",
      userName: "Kareena Sethi",
      rating: 5,
      title: "Small curve shape, immense richness",
      comment: "Do not mistake small size for low quality; real Mamra has that signature crescent curve and unmatched oil density.",
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-4",
      userName: "Dr. Homi Bhabha",
      rating: 5,
      title: "Authentic single-origin Iranian crop",
      comment: "Zero bitter seeds. Every single almond is sweet, dense, and packed with vitamin E and polyphenols.",
      createdAt: new Date(Date.now() - 23 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-5",
      userName: "Lata Mangeshwar",
      rating: 4,
      title: "Very rich taste and aroma",
      comment: "Tastes like real royal badam. A luxury worth every single rupee.",
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-6",
      userName: "Viren Merchant",
      rating: 5,
      title: "Worth the premium price tag",
      comment: "The tin packaging keeps the moisture and oil locked. 100% authentic Mamra almonds.",
      createdAt: new Date(Date.now() - 38 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-7",
      userName: "Nandini Piramal",
      rating: 5,
      title: "Extremely rich almond milk yield",
      comment: "Blended 10 soaked Mamra almonds for morning almond milk. Incredibly thick and naturally sweet.",
      createdAt: new Date(Date.now() - 46 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-8",
      userName: "Manish Malhotra",
      rating: 5,
      title: "Royal presentation & purity",
      comment: "The gold foil sealed tin makes it feel like an heirloom gift. Superb quality.",
      createdAt: new Date(Date.now() - 54 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-9",
      userName: "Rita Godrej",
      rating: 4,
      title: "Pure wellness in every bite",
      comment: "High oil content, natural sweetness, and authentic origin. Very pleased.",
      createdAt: new Date(Date.now() - 62 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-10",
      userName: "Alok Sanghavi",
      rating: 5,
      title: "True superfood grade",
      comment: "Highest grade Mamra I have tasted outside Iran. Truly exceptional.",
      createdAt: new Date(Date.now() - 71 * 86400000).toISOString(),
    },
    {
      _id: "rev-mamra-11",
      userName: "Sameer Nair",
      rating: 5,
      title: "Purest quality Mamra",
      comment: "Authentic mountain harvest. High oil content is easily noticeable.",
      createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
    },
  ],

  "afghani-organic-anjeer": [
    {
      _id: "rev-anjeer-1",
      userName: "Fazal Khan",
      rating: 5,
      title: "Soft honey core with crunchy seeds",
      comment: "Not dry or rubbery like market anjeer. These are succulent, plump, and have a rich honey syrup texture inside.",
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-2",
      userName: "Shobha De",
      rating: 5,
      title: "Zero added sugar — natural sweetness",
      comment: "Strung on traditional natural threads. Perfect digestive fiber for daily wellness.",
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-3",
      userName: "Rahul Bajaj",
      rating: 5,
      title: "Kandahar sun-dried quality",
      comment: "Large disc size with soft chew. Rich in natural calcium and potassium.",
      createdAt: new Date(Date.now() - 13 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-4",
      userName: "Anupama Chopra",
      rating: 4,
      title: "Naturally caramelized fruit sugar",
      comment: "Soaks into a tender, jam-like texture overnight. Excellent for post-dinner sweet craving.",
      createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-5",
      userName: "Devendra Fadnavis",
      rating: 5,
      title: "Fresh and soft texture",
      comment: "Figs stayed soft and moist throughout the month. Zero dust or hard stems.",
      createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-6",
      userName: "Rashmi Thackeray",
      rating: 5,
      title: "Clean garland disc figs",
      comment: "Hand-sorted and free of sand or gritty particles. The best anjeer online.",
      createdAt: new Date(Date.now() - 37 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-7",
      userName: "Jayant Sinha",
      rating: 5,
      title: "Delicious natural sweetness",
      comment: "Great fiber source. Plump and moist without artificial sugar coating.",
      createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-8",
      userName: "Sushma Swaraj",
      rating: 4,
      title: "Great for digestive health",
      comment: "Two soaked figs in the morning have worked wonders for gut health. Very pleased.",
      createdAt: new Date(Date.now() - 55 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-9",
      userName: "Kishore Biyani",
      rating: 5,
      title: "Grade A Kandahar export crop",
      comment: "Authentic Afghan garland anjeer. Beautiful pale amber color.",
      createdAt: new Date(Date.now() - 64 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-10",
      userName: "Geeta Phogat",
      rating: 5,
      title: "Athletic stamina booster",
      comment: "Natural carbs and iron for intense training sessions. Highly recommended.",
      createdAt: new Date(Date.now() - 72 * 86400000).toISOString(),
    },
    {
      _id: "rev-anjeer-11",
      userName: "Harsh Goenka",
      rating: 5,
      title: "Exquisite honeyed flavor",
      comment: "The fruit sugars are caramelized to perfection. Fresh and delicious.",
      createdAt: new Date(Date.now() - 82 * 86400000).toISOString(),
    },
  ],

  "royal-medjool-dates": [
    {
      _id: "rev-dates-1",
      userName: "Tariq Mansoor",
      rating: 5,
      title: "King size Medjool — melts in mouth!",
      comment: "Super jumbo size with paper-thin skin and a thick, fudge-like caramel center. The fruit of kings indeed.",
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-2",
      userName: "Sara Ali",
      rating: 5,
      title: "Rich caramel & brown sugar notes",
      comment: "Tastes like gourmet caramel confectionery, yet 100% natural fruit. Perfect pre-workout fuel.",
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-3",
      userName: "Ibrahim Qureshi",
      rating: 5,
      title: "Plump, moist and zero crystallisation",
      comment: "Fresh crop with soft moist flesh. Stored under cold lock so there is zero hard sugar crust.",
      createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-4",
      userName: "Zoya Akhtar",
      rating: 5,
      title: "Stuffed with walnuts — heavenly!",
      comment: "Split open a Medjool date and insert a Kashmiri walnut half. The ultimate healthy dessert.",
      createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-5",
      userName: "Kabir Bedi",
      rating: 4,
      title: "Large jumbo Jericho dates",
      comment: "Extremely satisfying size. Just 2 dates provide long-lasting natural energy.",
      createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-6",
      userName: "Nargis Fakhri",
      rating: 5,
      title: "High iron & instant vitality",
      comment: "Soft texture and rich aroma. Outstanding quality packaging box.",
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-7",
      userName: "Arbaaz Merchant",
      rating: 5,
      title: "Luxurious royal presentation",
      comment: "Ordered 5 boxes for Ramadan gifting. Every recipient called to ask where I bought them.",
      createdAt: new Date(Date.now() - 49 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-8",
      userName: "Fatima Sana",
      rating: 5,
      title: "Zero additives, 100% natural",
      comment: "No glucose coating or artificial shine. Pure authentic Medjool king dates.",
      createdAt: new Date(Date.now() - 58 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-9",
      userName: "Yusuf Pathan",
      rating: 4,
      title: "Rich energy for sports",
      comment: "Chewy, caramel-rich, packed with potassium and natural fructose. Top class.",
      createdAt: new Date(Date.now() - 66 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-10",
      userName: "Salma Agha",
      rating: 5,
      title: "Best dates available in India",
      comment: "Large, soft, and moist. Truly feels like royalty.",
      createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
    },
    {
      _id: "rev-dates-11",
      userName: "Naseeruddin Shah",
      rating: 5,
      title: "Plump, natural caramel sweetness",
      comment: "No sugar syrup or processing. Pure pristine sun-ripened Medjool dates.",
      createdAt: new Date(Date.now() - 85 * 86400000).toISOString(),
    },
  ],

  "afghan-green-raisins": [
    {
      _id: "rev-raisins-1",
      userName: "Urmila Matondkar",
      rating: 5,
      title: "Extra-long slender berries",
      comment: "Shade dried in traditional rooms. Vivid green color with sweet & tangy balance. Zero seeds.",
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-2",
      userName: "Girish Karnad",
      rating: 5,
      title: "Tart and sweet harmony",
      comment: "Not overly sugary like dark raisins. The natural acidity makes them incredibly refreshing.",
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-3",
      userName: "Asha Bhosle",
      rating: 5,
      title: "Soft chew without stickiness",
      comment: "Pristine green raisins, clean and free of stems. Wonderful in homemade kheer and pulao.",
      createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-4",
      userName: "Nitin Gadkari",
      rating: 4,
      title: "High iron content",
      comment: "Soaked in water overnight for daily blood wellness. Very good quality and clean.",
      createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-5",
      userName: "Rekha Ganesan",
      rating: 5,
      title: "Shade-dried green hue",
      comment: "Natural pale jade green without sulfur bleaching. True Afghani origin.",
      createdAt: new Date(Date.now() - 38 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-6",
      userName: "Sunil Gavaskar",
      rating: 5,
      title: "Energy booster on the go",
      comment: "Carry a small pouch during golf rounds. Instant clean glucose and hydration.",
      createdAt: new Date(Date.now() - 47 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-7",
      userName: "Madhuri Dixit",
      rating: 5,
      title: "Plump long raisins",
      comment: "Uniform slender shape and delightful sweet flavor. Very pleased with Viśvam.",
      createdAt: new Date(Date.now() - 57 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-8",
      userName: "Anil Kumble",
      rating: 4,
      title: "Great culinary quality",
      comment: "Adds an elegant royal touch to festive biryani and dessert platters.",
      createdAt: new Date(Date.now() - 67 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-9",
      userName: "Sharmila Tagore",
      rating: 5,
      title: "Exceptional purity",
      comment: "Sweet, juicy, and delicate skin. Excellent Afghan kishmish.",
      createdAt: new Date(Date.now() - 76 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-10",
      userName: "Pankaj Udhas",
      rating: 5,
      title: "Delightful natural snack",
      comment: "Great quality zip lock pouch ensures zero drying out. 5 stars.",
      createdAt: new Date(Date.now() - 84 * 86400000).toISOString(),
    },
    {
      _id: "rev-raisins-11",
      userName: "Kailash Kher",
      rating: 5,
      title: "Sweet and tangy delight",
      comment: "Long slender raisins with fresh fruity taste. Superb accompaniment to tea.",
      createdAt: new Date(Date.now() - 91 * 86400000).toISOString(),
    },
  ],

  "wild-dried-berries-mix": [
    {
      _id: "rev-berries-1",
      userName: "Tara Sutaria",
      rating: 5,
      title: "Succulent whole cranberries & wild blueberries!",
      comment: "Vibrant ruby cranberries and dark wild blueberries. Lightly sweetened with apple juice, not heavy corn syrup.",
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-2",
      userName: "Karan Johar",
      rating: 5,
      title: "High antioxidant immunity boost",
      comment: "Add a spoonful to Greek yogurt and granola every morning. Delicious tart flavor.",
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-3",
      userName: "Jacqueline Fernandez",
      rating: 5,
      title: "Juicy burst of natural berry juice",
      comment: "Plump whole berries that do not feel dry or leathery. Outstanding quality.",
      createdAt: new Date(Date.now() - 17 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-4",
      userName: "Manish Pandey",
      rating: 4,
      title: "Great salad topping",
      comment: "Pairs wonderfully with goat cheese, walnuts, and baby spinach salad. Very versatile.",
      createdAt: new Date(Date.now() - 26 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-5",
      userName: "Kiara Advani",
      rating: 5,
      title: "Urinary & skin health support",
      comment: "Pure wild harvest without artificial colors or preservatives. Tastes like real fresh berries.",
      createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-6",
      userName: "Sid Malhotra",
      rating: 5,
      title: "Pre-workout energy punch",
      comment: "Toss in trail mix before morning run. Fast, natural, antioxidant-rich fuel.",
      createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-7",
      userName: "Sonam Kapoor",
      rating: 5,
      title: "Clean packaging, plump berries",
      comment: "Glass jar looks chic and keeps moisture locked. Zero sticky clumps.",
      createdAt: new Date(Date.now() - 54 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-8",
      userName: "Anand Ahuja",
      rating: 4,
      title: "Very refreshing tangy berry mix",
      comment: "Natural ruby tones, deep blueberry flavor. Will repurchase regularly.",
      createdAt: new Date(Date.now() - 63 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-9",
      userName: "Kriti Sanon",
      rating: 5,
      title: "Favorite healthy sweet treat",
      comment: "Satisfies post-lunch sugar cravings without guilt. Highly recommended.",
      createdAt: new Date(Date.now() - 72 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-10",
      userName: "Varun Dhawan",
      rating: 5,
      title: "Top quality Pacific Northwest berries",
      comment: "Fresh, juicy, and rich in natural polyphenols. Top tier.",
      createdAt: new Date(Date.now() - 81 * 86400000).toISOString(),
    },
    {
      _id: "rev-berries-11",
      userName: "Shraddha Kapoor",
      rating: 5,
      title: "Bright and flavorful",
      comment: "The combination of cranberries and blueberries is delicious on morning oatmeal.",
      createdAt: new Date(Date.now() - 89 * 86400000).toISOString(),
    },
  ],

  "queensland-macadamia-nuts": [
    {
      _id: "rev-mac-1",
      userName: "Chef Sanjeev Kapoor",
      rating: 5,
      title: "Silky buttery crunch — Style 1 whole kernels!",
      comment: "Macadamias are the world's most luxurious nut. These Australian Style 1 whole kernels are ultra-buttery and fresh.",
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-2",
      userName: "Rhea Chakraborty",
      rating: 5,
      title: "Keto holy grail nut",
      comment: "High in healthy monounsaturated fats and low carb. The rich, velvety texture is pure indulgence.",
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-3",
      userName: "Chef Vikas Khanna",
      rating: 5,
      title: "Subterranean Australian soil sweetness",
      comment: "Lightly cream-colored with zero bitter notes. A rare culinary treasure.",
      createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-4",
      userName: "Dia Mirza",
      rating: 5,
      title: "Cold-shelled perfection",
      comment: "Cold shelling preserves the fragile oil structure. Truly remarkable mouthfeel.",
      createdAt: new Date(Date.now() - 31 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-5",
      userName: "Ranveer Singh",
      rating: 4,
      title: "Pure decadence",
      comment: "Super rich, buttery, and filling. Just 4-5 nuts give you a massive energy boost.",
      createdAt: new Date(Date.now() - 41 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-6",
      userName: "Deepika Padukone",
      rating: 5,
      title: "Exotic and premium quality",
      comment: "Flawlessly packed in heavy glass jar. Premium gifting quality.",
      createdAt: new Date(Date.now() - 51 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-7",
      userName: "Nikhil Kamath",
      rating: 5,
      title: "Best macadamias in India",
      comment: "Clean sourcing, unbroken whole spheres. Worth the premium price.",
      createdAt: new Date(Date.now() - 61 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-8",
      userName: "Rohit Shetty",
      rating: 4,
      title: "Smooth, velvety texture",
      comment: "Very high natural fat content. Great with dark roast espresso.",
      createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-9",
      userName: "Mira Rajput",
      rating: 5,
      title: "Unrivaled luxury snack",
      comment: "Kids and elders both loved the smooth creamy bite. 10/10.",
      createdAt: new Date(Date.now() - 79 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-10",
      userName: "Shahid Kapoor",
      rating: 5,
      title: "Clean healthy fats",
      comment: "Best fuel for intermittent fasting windows. Top quality.",
      createdAt: new Date(Date.now() - 88 * 86400000).toISOString(),
    },
    {
      _id: "rev-mac-11",
      userName: "Farah Khan",
      rating: 5,
      title: "Heavenly rich taste",
      comment: "Ultra creamy and fresh. Easily the best macadamia nuts in the country.",
      createdAt: new Date(Date.now() - 94 * 86400000).toISOString(),
    },
  ],

  "7-in-1-superseeds-mix": [
    {
      _id: "rev-seeds-1",
      userName: "Milind Soman",
      rating: 5,
      title: "The daily health powerhouse!",
      comment: "Pumpkin, Sunflower, Flax, Chia, Sesame, Watermelon and Hemp seeds dry-roasted without oil. High zinc & plant protein.",
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-2",
      userName: "Ankita Konwar",
      rating: 5,
      title: "Light pink salt crunch",
      comment: "Zero oily residue. Just clean, light roasted seeds with a delicate salty crunch. Sprinkled over smoothie bowls daily.",
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-3",
      userName: "Shilpa Shetty",
      rating: 5,
      title: "Complete 7-seed synergy",
      comment: "Getting all 7 superseeds in one balanced mix saves so much kitchen prep time. Great for hair and skin health.",
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-4",
      userName: "Sunil Grover",
      rating: 4,
      title: "Crispy and guilt-free",
      comment: "Keep a pouch on my work desk. Whenever I want to munch, this is healthy and satisfying.",
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-5",
      userName: "Mandira Bedi",
      rating: 5,
      title: "High magnesium & omega 3",
      comment: "Noticeable boost in recovery after workouts. Top quality seed harvest.",
      createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-6",
      userName: "Rajkummar Rao",
      rating: 5,
      title: "Fresh roast, zero bitterness",
      comment: "Flax and hemp seeds are notoriously hard to roast without turning bitter; Viśvam nailed the roasting time.",
      createdAt: new Date(Date.now() - 42 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-7",
      userName: "Patralekhaa",
      rating: 5,
      title: "Great on avocado toast",
      comment: "Adds a fantastic texture and nutty crunch to morning sourdough toasts.",
      createdAt: new Date(Date.now() - 52 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-8",
      userName: "Abhinav Bindra",
      rating: 4,
      title: "Clean nutritional profile",
      comment: "Excellent plant protein source with rich zinc profile. Very clean.",
      createdAt: new Date(Date.now() - 62 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-9",
      userName: "Sania Mirza",
      rating: 5,
      title: "Freshness locked pouch",
      comment: "No stale seed oil odor. Remains fragrant and crisp for weeks.",
      createdAt: new Date(Date.now() - 72 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-10",
      userName: "Mary Kom",
      rating: 5,
      title: "Champion wellness snack",
      comment: "Nutrient dense and energetic. 5 stars from me.",
      createdAt: new Date(Date.now() - 82 * 86400000).toISOString(),
    },
    {
      _id: "rev-seeds-11",
      userName: "Bhaichung Bhutia",
      rating: 5,
      title: "Superb daily stamina blend",
      comment: "Great quality seeds, crunchy and roasted to perfection.",
      createdAt: new Date(Date.now() - 92 * 86400000).toISOString(),
    },
  ],

  "royal-heritage-gift-box": [
    {
      _id: "rev-gift-1",
      userName: "Mukesh Ambani",
      rating: 5,
      title: "Opulent executive corporate gifting",
      comment: "Ordered 50 boxes for our executive partners. The emerald & gold presentation, magnetic closure, and curated dry fruits made a lasting impression.",
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-2",
      userName: "Nita Ambani",
      rating: 5,
      title: "Exquisite craftsmanship & ribboning",
      comment: "Every compartment featuring Jumbo Almonds, W240 Cashews, Kashmiri Walnuts, and Roasted Pistachios was pristine.",
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-3",
      userName: "Adar Poonawalla",
      rating: 5,
      title: "Gold standard Diwali gifting",
      comment: "The highest grade nuts presented with true royal dignity. Arrived flawlessly packed.",
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-4",
      userName: "Natasha Poonawalla",
      rating: 5,
      title: "Stunning keepsake gift box",
      comment: "The box itself is a work of art. The recipients were blown away by the quality of the nuts inside.",
      createdAt: new Date(Date.now() - 27 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-5",
      userName: "Kumar Mangalam Birla",
      rating: 5,
      title: "Flawless packaging and freshness",
      comment: "Individual compartments ensure the nuts taste as fresh as the day they were harvested.",
      createdAt: new Date(Date.now() - 37 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-6",
      userName: "Ananya Birla",
      rating: 5,
      title: "Pure luxury gift experience",
      comment: "The unboxing experience is magnificent. Highly recommended for weddings and VIP client gifts.",
      createdAt: new Date(Date.now() - 48 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-7",
      userName: "Ratan Tata",
      rating: 5,
      title: "Dignified quality and care",
      comment: "Exemplary attention to detail in sourcing and presentation. Truly royal.",
      createdAt: new Date(Date.now() - 58 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-8",
      userName: "Azim Premji",
      rating: 4,
      title: "Splendid assortment of royal nuts",
      comment: "Generous portions in each section. Delivered on time with premium courier care.",
      createdAt: new Date(Date.now() - 68 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-9",
      userName: "Roshni Nadar",
      rating: 5,
      title: "VIP client gifting perfection",
      comment: "Our board members and clients were thoroughly delighted. Will be our permanent annual gift partner.",
      createdAt: new Date(Date.now() - 78 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-10",
      userName: "Kiran Mazumdar Shaw",
      rating: 5,
      title: "Unmatched elegance and taste",
      comment: "Five stars across the board for aesthetics, freshness, and heritage quality.",
      createdAt: new Date(Date.now() - 88 * 86400000).toISOString(),
    },
    {
      _id: "rev-gift-11",
      userName: "Gautam Adani",
      rating: 5,
      title: "Exceptional corporate gift",
      comment: "Unmatched presentation and freshness. Perfect for festive celebrations.",
      createdAt: new Date(Date.now() - 95 * 86400000).toISOString(),
    },
  ],

  "festive-nut-berry-celebration": [
    {
      _id: "rev-festive-1",
      userName: "Shashi Tharoor",
      rating: 5,
      title: "A confluence of artisanal excellence",
      comment: "An opulent octagonal presentation featuring Mamra almonds, Wild Berries, King Dates, and Macadamia nuts. Exquisite in every sense.",
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-2",
      userName: "Priyanka Chopra",
      rating: 5,
      title: "The centerpiece of our festive table",
      comment: "The combination of vibrant berries and royal nuts looks stunning when entertaining guests. Everyone loved it.",
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-3",
      userName: "Nick Jonas",
      rating: 5,
      title: "Incredible flavor variety",
      comment: "The sweet Medjool dates and savory roasted nuts pair so well together. Best gift platter ever.",
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-4",
      userName: "Anil Ambani",
      rating: 4,
      title: "Grand festive presentation",
      comment: "Generous 1kg assortment. Beautiful ribbon and personalized gift card included.",
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-5",
      userName: "Tina Ambani",
      rating: 5,
      title: "Royal heritage aesthetics",
      comment: "The warm gold and sand tones on the box are timeless. Freshness was intact across all 6 compartments.",
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-6",
      userName: "Gauri Khan",
      rating: 5,
      title: "Designer grade dry fruit hamper",
      comment: "The aesthetic harmony and tactile quality of the box are unmatched in the Indian market.",
      createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-7",
      userName: "Shah Rukh Khan",
      rating: 5,
      title: "Pure royal indulgence",
      comment: "Each item reflects supreme quality. A gift fit for royalty.",
      createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-8",
      userName: "Karan Adani",
      rating: 5,
      title: "Top tier festive collection",
      comment: "Impeccable packaging and fast delivery. Very satisfied.",
      createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-9",
      userName: "Parineeti Chopra",
      rating: 4,
      title: "Wonderful gourmet variety",
      comment: "The wild berries and macadamia nuts make this platter stand out from regular gift boxes.",
      createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-10",
      userName: "Raghav Chadha",
      rating: 5,
      title: "Unrivaled quality and taste",
      comment: "Extremely fresh and delicious. A staple for all family celebrations.",
      createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    },
    {
      _id: "rev-festive-11",
      userName: "Kareena Kapoor Khan",
      rating: 5,
      title: "Exquisite festive hamper",
      comment: "Luxurious arrangement, delicious nuts, and stunning gift box.",
      createdAt: new Date(Date.now() - 96 * 86400000).toISOString(),
    },
  ],
};
