/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as ChaiRouteImport } from './routes/chai'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as DriedFruitsRouteImport } from './routes/dried-fruits'
import { Route as ExoticSeedsRouteImport } from './routes/exotic-seeds'
import { Route as NutsRouteImport } from './routes/nuts'
import { Route as PlatesRouteImport } from './routes/plates'
import { Route as SnacksRouteImport } from './routes/snacks'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SweetsRouteImport } from './routes/sweets'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaiRoute = ChaiRouteImport.update({
  id: '/chai',
  path: '/chai',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const DriedFruitsRoute = DriedFruitsRouteImport.update({
  id: '/dried-fruits',
  path: '/dried-fruits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExoticSeedsRoute = ExoticSeedsRouteImport.update({
  id: '/exotic-seeds',
  path: '/exotic-seeds',
  getParentRoute: () => rootRouteImport,
} as any)
const NutsRoute = NutsRouteImport.update({
  id: '/nuts',
  path: '/nuts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesRoute = PlatesRouteImport.update({
  id: '/plates',
  path: '/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const SnacksRoute = SnacksRouteImport.update({
  id: '/snacks',
  path: '/snacks',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetsRoute = SweetsRouteImport.update({
  id: '/sweets',
  path: '/sweets',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/chai': typeof ChaiRoute
  '/combos': typeof CombosRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/nuts': typeof NutsRoute
  '/plates': typeof PlatesRoute
  '/snacks': typeof SnacksRoute
  '/story': typeof StoryRoute
  '/sweets': typeof SweetsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/chai': typeof ChaiRoute
  '/combos': typeof CombosRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/nuts': typeof NutsRoute
  '/plates': typeof PlatesRoute
  '/snacks': typeof SnacksRoute
  '/story': typeof StoryRoute
  '/sweets': typeof SweetsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/chai': typeof ChaiRoute
  '/combos': typeof CombosRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/nuts': typeof NutsRoute
  '/plates': typeof PlatesRoute
  '/snacks': typeof SnacksRoute
  '/story': typeof StoryRoute
  '/sweets': typeof SweetsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buttons'
    | '/chai'
    | '/combos'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/nuts'
    | '/plates'
    | '/snacks'
    | '/story'
    | '/sweets'
    | '/menu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buttons'
    | '/chai'
    | '/combos'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/nuts'
    | '/plates'
    | '/snacks'
    | '/story'
    | '/sweets'
    | '/menu/$slug'
  id:
    | '__root__'
    | '/'
    | '/buttons'
    | '/chai'
    | '/combos'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/nuts'
    | '/plates'
    | '/snacks'
    | '/story'
    | '/sweets'
    | '/menu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonsRoute: typeof ButtonsRoute
  ChaiRoute: typeof ChaiRoute
  CombosRoute: typeof CombosRoute
  DriedFruitsRoute: typeof DriedFruitsRoute
  ExoticSeedsRoute: typeof ExoticSeedsRoute
  NutsRoute: typeof NutsRoute
  PlatesRoute: typeof PlatesRoute
  SnacksRoute: typeof SnacksRoute
  StoryRoute: typeof StoryRoute
  SweetsRoute: typeof SweetsRoute
  MenuSlugRoute: typeof MenuSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chai': {
      id: '/chai'
      path: '/chai'
      fullPath: '/chai'
      preLoaderRoute: typeof ChaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dried-fruits': {
      id: '/dried-fruits'
      path: '/dried-fruits'
      fullPath: '/dried-fruits'
      preLoaderRoute: typeof DriedFruitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exotic-seeds': {
      id: '/exotic-seeds'
      path: '/exotic-seeds'
      fullPath: '/exotic-seeds'
      preLoaderRoute: typeof ExoticSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuts': {
      id: '/nuts'
      path: '/nuts'
      fullPath: '/nuts'
      preLoaderRoute: typeof NutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates': {
      id: '/plates'
      path: '/plates'
      fullPath: '/plates'
      preLoaderRoute: typeof PlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snacks': {
      id: '/snacks'
      path: '/snacks'
      fullPath: '/snacks'
      preLoaderRoute: typeof SnacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweets': {
      id: '/sweets'
      path: '/sweets'
      fullPath: '/sweets'
      preLoaderRoute: typeof SweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonsRoute: ButtonsRoute,
  ChaiRoute: ChaiRoute,
  CombosRoute: CombosRoute,
  DriedFruitsRoute: DriedFruitsRoute,
  ExoticSeedsRoute: ExoticSeedsRoute,
  NutsRoute: NutsRoute,
  PlatesRoute: PlatesRoute,
  SnacksRoute: SnacksRoute,
  StoryRoute: StoryRoute,
  SweetsRoute: SweetsRoute,
  MenuSlugRoute: MenuSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
