/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R10PdfRouteImport } from './routes/10-pdf'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DomainGuideRouteImport } from './routes/domain-guide'
import { Route as DriedFruitsRouteImport } from './routes/dried-fruits'
import { Route as ExoticSeedsRouteImport } from './routes/exotic-seeds'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as GourmetRouteImport } from './routes/gourmet'
import { Route as NutsRouteImport } from './routes/nuts'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProposalPdfRouteImport } from './routes/proposal-pdf'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R10PdfRoute = R10PdfRouteImport.update({
  id: '/10-pdf',
  path: '/10-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainGuideRoute = DomainGuideRouteImport.update({
  id: '/domain-guide',
  path: '/domain-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DriedFruitsRoute = DriedFruitsRouteImport.update({
  id: '/dried-fruits',
  path: '/dried-fruits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExoticSeedsRoute = ExoticSeedsRouteImport.update({
  id: '/exotic-seeds',
  path: '/exotic-seeds',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const GourmetRoute = GourmetRouteImport.update({
  id: '/gourmet',
  path: '/gourmet',
  getParentRoute: () => rootRouteImport,
} as any)
const NutsRoute = NutsRouteImport.update({
  id: '/nuts',
  path: '/nuts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalPdfRoute = ProposalPdfRouteImport.update({
  id: '/proposal-pdf',
  path: '/proposal-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/10-pdf': typeof R10PdfRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design': typeof DesignRoute
  '/domain-guide': typeof DomainGuideRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/gifting': typeof GiftingRoute
  '/gourmet': typeof GourmetRoute
  '/nuts': typeof NutsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proposal-pdf': typeof ProposalPdfRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/10-pdf': typeof R10PdfRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design': typeof DesignRoute
  '/domain-guide': typeof DomainGuideRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/gifting': typeof GiftingRoute
  '/gourmet': typeof GourmetRoute
  '/nuts': typeof NutsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proposal-pdf': typeof ProposalPdfRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/10-pdf': typeof R10PdfRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design': typeof DesignRoute
  '/domain-guide': typeof DomainGuideRoute
  '/dried-fruits': typeof DriedFruitsRoute
  '/exotic-seeds': typeof ExoticSeedsRoute
  '/gifting': typeof GiftingRoute
  '/gourmet': typeof GourmetRoute
  '/nuts': typeof NutsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proposal-pdf': typeof ProposalPdfRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/menu/$slug': typeof MenuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/10-pdf'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/cookies'
    | '/design'
    | '/domain-guide'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/gifting'
    | '/gourmet'
    | '/nuts'
    | '/order-success'
    | '/privacy'
    | '/profile'
    | '/proposal-pdf'
    | '/returns'
    | '/shipping'
    | '/story'
    | '/terms'
    | '/menu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/10-pdf'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/cookies'
    | '/design'
    | '/domain-guide'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/gifting'
    | '/gourmet'
    | '/nuts'
    | '/order-success'
    | '/privacy'
    | '/profile'
    | '/proposal-pdf'
    | '/returns'
    | '/shipping'
    | '/story'
    | '/terms'
    | '/menu/$slug'
  id:
    | '__root__'
    | '/'
    | '/10-pdf'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/cookies'
    | '/design'
    | '/domain-guide'
    | '/dried-fruits'
    | '/exotic-seeds'
    | '/gifting'
    | '/gourmet'
    | '/nuts'
    | '/order-success'
    | '/privacy'
    | '/profile'
    | '/proposal-pdf'
    | '/returns'
    | '/shipping'
    | '/story'
    | '/terms'
    | '/menu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R10PdfRoute: typeof R10PdfRoute
  CheckoutRoute: typeof CheckoutRoute
  CombosRoute: typeof CombosRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DesignRoute: typeof DesignRoute
  DomainGuideRoute: typeof DomainGuideRoute
  DriedFruitsRoute: typeof DriedFruitsRoute
  ExoticSeedsRoute: typeof ExoticSeedsRoute
  GiftingRoute: typeof GiftingRoute
  GourmetRoute: typeof GourmetRoute
  NutsRoute: typeof NutsRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProposalPdfRoute: typeof ProposalPdfRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  StoryRoute: typeof StoryRoute
  TermsRoute: typeof TermsRoute
  MenuSlugRoute: typeof MenuSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10-pdf': {
      id: '/10-pdf'
      path: '/10-pdf'
      fullPath: '/10-pdf'
      preLoaderRoute: typeof R10PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain-guide': {
      id: '/domain-guide'
      path: '/domain-guide'
      fullPath: '/domain-guide'
      preLoaderRoute: typeof DomainGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dried-fruits': {
      id: '/dried-fruits'
      path: '/dried-fruits'
      fullPath: '/dried-fruits'
      preLoaderRoute: typeof DriedFruitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exotic-seeds': {
      id: '/exotic-seeds'
      path: '/exotic-seeds'
      fullPath: '/exotic-seeds'
      preLoaderRoute: typeof ExoticSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gourmet': {
      id: '/gourmet'
      path: '/gourmet'
      fullPath: '/gourmet'
      preLoaderRoute: typeof GourmetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuts': {
      id: '/nuts'
      path: '/nuts'
      fullPath: '/nuts'
      preLoaderRoute: typeof NutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-pdf': {
      id: '/proposal-pdf'
      path: '/proposal-pdf'
      fullPath: '/proposal-pdf'
      preLoaderRoute: typeof ProposalPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R10PdfRoute: R10PdfRoute,
  CheckoutRoute: CheckoutRoute,
  CombosRoute: CombosRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DesignRoute: DesignRoute,
  DomainGuideRoute: DomainGuideRoute,
  DriedFruitsRoute: DriedFruitsRoute,
  ExoticSeedsRoute: ExoticSeedsRoute,
  GiftingRoute: GiftingRoute,
  GourmetRoute: GourmetRoute,
  NutsRoute: NutsRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProposalPdfRoute: ProposalPdfRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  StoryRoute: StoryRoute,
  TermsRoute: TermsRoute,
  MenuSlugRoute: MenuSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
